---
# tasks file for nexii_apache
- name: ensure apache is installed
  apt: name=apache2 state=present 
- name: ensure apache is started
  service: name=apache2 state=started enabled=yes
- name: copy the root document
  copy: src=/etc/ansible/nexii_lamp/nexii_apache/templates/image1.jpg dest=/var/www/html/cloud.png
- name: copy the configuration file
  template: src=index.j2 dest=/var/www/html/index.html
  notify: restart apache service 
- name: install php server
  apt: name= "{{ item }}" state=present
  with_items:
    - php5
    - libapache2-mod-php5
- name: copy ile to document root
  copy: src=/var/www/html/nexiilabs-logo.jpg dest=/var/www/html/nexiilabs-logo.jpg
- name: copy the application code to document root
  template: src=index.j2 dest=/var/www/html/index.php
  notify: restart apache service
- name: ensure mysqy-server is installed
  apt: name=mysql-server state=present
- name: starting mysql-server
  service: name=mysql state=started enabled=yes
- name:  create application database
  mysql_db: name={{ item }} state=present
  with_items:
   - ansible_db01
   - ansible_db02
- name: create application user
  mysql_user: name=vagrant password=vagrant priv=*.*:ALL state=present


